### ISSUE TITLE
Postgres indexer broken

### ISSUE THREAD

**Issue by tchardin** [latticexyz/mud#1923]
```
2023-11-12T16:34:38.567Z mud:block-events-stream getting logs { fromBlock: 242410n, toBlock: 242510n }
2023-11-12T16:34:38.569Z mud:store-sync:postgres Store_SpliceStaticData {
 address: '0x6e9474e9c83676b9a71133ff96db43e7aa0a4342',
 topics: [
 '0x8c0b5119d4cec7b284c6b1b39252a03d1e2f2d7451a5895562524c113bb952be',
 '0x7462426572727900000000000000000041646d696e0000000000000000000000'
 ],
 data: '0x00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000014f7f28af176fd3eba2580559349f4a3962ce58dc0000000000000000000000000',
 blockNumber: 241400n,
 transactionHash: '0x6431ccf4fa6d09e49ceda6a971fed4dd7be7f2842ee640e1fb75e53d84a1b070',
 transactionIndex: 1,
 blockHash: '0x69f2904e7bb027e386784d4cc78908f93792436f7f9b61e2ac1861a92ee2680e',
 logIndex: 0,
 removed: false,
 args: {
 tableId: '0x7462426572727900000000000000000041646d696e0000000000000000000000',
 keyTuple: [],
 start: 0,
 data: '0xf7f28af176fd3eba2580559349f4a3962ce58dc0'
 },
 eventName: 'Store_SpliceStaticData'
}
2023-11-12T16:34:38.571Z mud:block-events-stream getting logs { fromBlock: 242511n, toBlock: 242611n }
2023-11-12T16:34:38.574Z mud:block-events-stream getting logs { fromBlock: 242612n, toBlock: 242712n }
2023-11-12T16:34:38.622Z mud:block-events-stream getting logs { fromBlock: 242713n, toBlock: 242813n }
2023-11-12T16:34:38.625Z mud:block-events-stream getting logs { fromBlock: 242814n, toBlock: 242914n }

/app/node_modules/.pnpm/rxjs@7.5.5/node_modules/rxjs/dist/cjs/internal/util/reportUnhandledError.js:13
 throw err;
 ^

PostgresError: relation "0x6E9474e9c83676B9A71133FF96Db43E7AA0a4342__Berry.Admin" does not exist
 at ErrorResponse (file:///app/node_modules/.pnpm/postgres@3.3.5/node_modules/postgres/src/connection.js:771:26)
 at handle (file:///app/node_modules/.pnpm/postgres@3.3.5/node_modules/postgres/src/connection.js:473:6)
 at Socket.data (file:///app/node_modules/.pnpm/postgres@3.3.5/node_modules/postgres/src/connection.js:314:9)
 at Socket.emit (node:events:517:28)
 at Socket.emit (node:domain:489:12)
 at addChunk (node:internal/streams/readable:335:12)
 at readableAddChunk (node:internal/streams/readable:308:9)
 at Readable.push (node:internal/streams/readable:245:10)
 at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by ludns** [comment]
Doesn't closing this with the PR above mean that data can get desynced in the indexer? Why are we skipping updates?

**Comment by holic** [comment]
For problematic tables/worlds, yes, but we don't have time for a more thorough fix right now.
