### ISSUE TITLE
Restart the world when `PostDeploy.s.sol` is changed

### ISSUE THREAD

**Issue by qbzzt** [latticexyz/mud#1926]
Right now when I modify it `pnpm dev` attempts to do some kind of partial redeploy, and register tables that are already registered. Naturally, this fails.

```
[contracts] Contracts changed, queuing deploy...
[contracts] Rebuilding and upgrading world...
[contracts] 
[contracts]  Deploying MUD contracts to RPC http://127.0.0.1:8545 
[contracts] 
[contracts] running "forge build"
[contracts] Compiling 1 files with 0.8.21
[contracts] Solc 0.8.21 finished in 4.45s
[contracts] Compiler run successful!
[contracts] (node:82528) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
[contracts] (Use `node --trace-warnings ...` to show where the warning was created)
[contracts] (node:82528) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
[contracts] Deploying from 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
[contracts] 
[contracts]  Error while attempting deploy 
[contracts] 
[contracts] ContractFunctionExecutionError: The contract function "registerTable" reverted.
[contracts] 
[contracts] Error: Store_TableAlreadyExists(bytes32 tableId, string tableIdString)
[contracts]                                (0x746200000000000000000000000000004d6170436f6e66696700000000000000, tbMapConfig)
[contracts]  
[contracts] Contract Call:
[contracts]   address:   0x6e9474e9c83676b9a71133ff96db43e7aa0a4342
[contracts]   function:  registerTable(bytes32 tableId, bytes32 fieldLayout, bytes32 keySchema, bytes32 valueSchema, string[] keyNames, string[] fieldNames)
[contracts]   args:                   (0x746200000000000000000000000000004d6170436f6e66696700000000000000, 0x0008020104040000000000000000000000000000000000000000000000000000, 0x0000000000000000000000000000000000000000000000000000000000000000, 0x000802010303c400000000000000000000000000000000000000000000000000, [], ["width","height","terrain"])
[contracts]   sender:    0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
[contracts] 
[contracts] Docs: https://viem.sh/docs/contract/simulateContract.html
[contracts] Version: viem@1.13.2
[contracts]     at getContractError (file:///Users/qbzzt/emojimon/node_modules/.pnpm/viem@1.14.0_typescript@5.1.6_zod@3.22.4/node_modules/viem/_esm/utils/errors/getContractError.js:26:12)
[contracts]     at simulateContract (file:///Users/qbzzt/emojimon/node_modules/.pnpm/viem@1.14.0_typescript@5.1.6_zod@3.22.4/node_modules/viem/_esm/actions/public/simulateContract.js:72:15)
[contracts]     ... 3 lines matching cause stack trace ...
[contracts]     at async RetryOperation._fn (file:///Users/qbzzt/emojimon/node_modules/.pnpm/p-retry@5.1.2/node_modules/p-retry/index.js:55:13) {
[contracts]   details: undefined,
[contracts]   docsPath: '/docs/contract/simulateContract',
[contracts]   metaMessages: [
[contracts]     'Error: Store_TableAlreadyExists(bytes32 tableId, string tableIdString)',
[contracts]     '                               (0x746200000000000000000000000000004d6170436f6e66696700000000000000, tb\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00MapConfig\x00\x00\x00\x00\x00\x00\x00)',
[contracts]     ' ',
[contracts]     'Contract Call:',
[contracts]     '  address:   0x6e9474e9c83676b9a71133ff96db43e7aa0a4342\n' +
[contracts]       '  function:  registerTable(bytes32 tableId, bytes32 fieldLayout, bytes32 keySchema, bytes32 valueSchema, string[] keyNames, string[] fieldNames)\n' +
[contracts]       '  args:                   (0x746200000000000000000000000000004d6170436f6e66696700000000000000, 0x0008020104040000000000000000000000000000000000000000000000000000, 0x0000000000000000000000000000000000000000000000000000000000000000, 0x000802010303c400000000000000000000000000000000000000000000000000, [], ["width","height","terrain"])\n' +
[contracts]       '  sender:    0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266'
[contracts]   ],
[contracts]   shortMessage: 'The contract function "registerTable" reverted.',
[contracts]   version: 'viem@1.13.2',
[contracts]   cause: ContractFunctionRevertedError: The contract function "registerTable" reverted.
[contracts]   
[contracts]   Error: Store_TableAlreadyExists(bytes32 tableId, string tableIdString)
[contracts]                                  (0x746200000000000000000000000000004d6170436f6e66696700000000000000, tbMapConfig)
[contracts]   
[contracts]   Version: viem@1.13.2
[contracts]       at file:///Users/qbzzt/emojimon/node_modules/.pnpm/viem@1.14.0_typescript@5.1.6_zod@3.22.4/node_modules/viem/_esm/utils/errors/getContractError.js:17:20
[contracts]       at getContractError (file:///Users/qbzzt/emojimon/node_modules/.pnpm/viem@1.14.0_typescript@5.1.6_zod@3.22.4/node_modules/viem/_esm/utils/errors/getContractError.js:25:7)
[contracts]       at simulateContract (file:///Users/qbzzt/emojimon/node_modules/.pnpm/viem@1.14.0_typescript@5.1.6_zod@3.22.4/node_modules/viem/_esm/actions/public/simulateContract.js:72:15)
[contracts]       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[contracts]       at async a (file:///Users/qbzzt/emojimon/node_modules/.pnpm/@latticexyz+common@2.0.0-next.14_typescript@5.1.6_zod@3.22.4/node_modules/@latticexyz/common/dist/index.js:1:2084)
[contracts]       at async v (file:///Users/qbzzt/emojimon/node_modules/.pnpm/@latticexyz+common@2.0.0-next.14_typescript@5.1.6_zod@3.22.4/node_modules/@latticexyz/common/dist/index.js:1:2147)
[contracts]       at async RetryOperation._fn (file:///Users/qbzzt/emojimon/node_modules/.pnpm/p-retry@5.1.2/node_modules/p-retry/index.js:55:13) {
[contracts]     details: undefined,
[contracts]     docsPath: undefined,
[contracts]     metaMessages: [
[contracts]       'Error: Store_TableAlreadyExists(bytes32 tableId, string tableIdString)',
[contracts]       '                               (0x746200000000000000000000000000004d6170436f6e66696700000000000000, tb\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00MapConfig\x00\x00\x00\x00\x00\x00\x00)'
[contracts]     ],
[contracts]     shortMessage: 'The contract function "registerTable" reverted.',
[contracts]     version: 'viem@1.13.2',
[contracts]     data: {
[contracts]       abiItem: [Object],
[contracts]       args: [Array],
[contracts]       errorName: 'Store_TableAlreadyExists'
[contracts]     },
[contracts]     reason: undefined,
[contracts]     signature: undefined
[contracts]   },

```

**Comment by holic** [comment]
By default, `PostDeploy` should only be run once for a world, unless you enable `--alwaysRunPostDeploy` in your `mud dev-contracts` command.
