### ISSUE TITLE
Deploying MUD project fails with `Error: gas required exceeds allowance (0)`

### ISSUE THREAD

**Issue by emersonhsieh** [latticexyz/mud#2065]
To reproduce:
1. Clone the following repository: https://github.com/emersonhsieh/emojimon
2. Add a private key with Redstone Holesky ETH to `packages/contracts/.env`
3. `pnpm run deploy:redstone`

This issue appears on MUD version `2.0.0-main-735d957c` and also happens on other chains (e.g. Caldera).

Complete logs:

```
emersonhsieh@MacBook-Pro-2023 contracts % pnpm run deploy:redstone

> contracts@0.0.0 deploy:redstone /Users/emersonhsieh/london-aw/emojimon/packages/contracts
> pnpm run build && pnpm mud deploy --profile=redstone


> contracts@0.0.0 build /Users/emersonhsieh/london-aw/emojimon/packages/contracts
> forge clean && forge build

[⠒] Compiling...
[⠘] Compiling 67 files with 0.8.13
[⠊] Solc 0.8.13 finished in 2.68s
Compiler run successful with warnings:
Warning (2072): Unused local variable.
  --> script/PostDeploy.s.sol:11:5:
   |
11 |     IWorld world = IWorld(worldAddress);
   |     ^^^^^^^^^^^^

Warning (2018): Function state mutability can be restricted to pure
   --> /Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@latticexyz+store@2.0.0-alpha.1.177_typescript@5.0.4/node_modules/@latticexyz/store/src/codegen/tables/Hooks.sol:187:3:
    |
187 |   function encode(address[] memory value) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> /Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@latticexyz+store@2.0.0-alpha.1.177_typescript@5.0.4/node_modules/@latticexyz/store/src/codegen/tables/Callbacks.sol:187:3:
    |
187 |   function encode(bytes24[] memory value) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> /Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@latticexyz+store@2.0.0-alpha.1.177_typescript@5.0.4/node_modules/@latticexyz/store/src/codegen/tables/StoreMetadata.sol:388:3:
    |
388 |   function encode(string memory tableName, bytes memory abiEncodedFieldNames) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> /Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@latticexyz+store@2.0.0-alpha.1.177_typescript@5.0.4/node_modules/@latticexyz/store/src/codegen/tables/Mixed.sol:459:3:
    |
459 |   function encode(uint32 u32, uint128 u128, uint32[] memory a32, string memory s) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> /Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@latticexyz+store@2.0.0-alpha.1.177_typescript@5.0.4/node_modules/@latticexyz/store/src/codegen/tables/Vector2.sol:199:3:
    |
199 |   function encode(uint32 x, uint32 y) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> node_modules/@latticexyz/store/src/codegen/tables/Hooks.sol:187:3:
    |
187 |   function encode(address[] memory value) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> node_modules/@latticexyz/store/src/codegen/tables/Callbacks.sol:187:3:
    |
187 |   function encode(bytes24[] memory value) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> node_modules/@latticexyz/store/src/codegen/tables/StoreMetadata.sol:388:3:
    |
388 |   function encode(string memory tableName, bytes memory abiEncodedFieldNames) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> node_modules/@latticexyz/store/src/codegen/tables/Mixed.sol:459:3:
    |
459 |   function encode(uint32 u32, uint128 u128, uint32[] memory a32, string memory s) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> node_modules/@latticexyz/store/src/codegen/tables/Vector2.sol:199:3:
    |
199 |   function encode(uint32 x, uint32 y) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> src/codegen/tables/Movable.sol:103:3:
    |
103 |   function encode(bool value) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> src/codegen/tables/Player.sol:103:3:
    |
103 |   function encode(bool value) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

Warning (2018): Function state mutability can be restricted to pure
   --> src/codegen/tables/Position.sol:184:3:
    |
184 |   function encode(uint32 x, uint32 y) internal view returns (bytes memory) {
    |   ^ (Relevant source part starts here and spans across multiple lines).

(node:92309) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:92309) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

 Deploying MUD contracts with profile redstone to RPC https://rpc.holesky.redstone.xyz 

running "forge build"
[⠊] Compiling...
No files changed, compilation skipped
Initial nonce 0
running "cast block-number --rpc-url https://rpc.holesky.redstone.xyz"
Start deployment at block 1603403
executing deployment of World with nonce 0
Deploying MapSystem
executing deployment of CoreModule with nonce 1
executing deployment of KeysWithValueModule with nonce 2
executing deployment of KeysInTableModule with nonce 3
executing deployment of UniqueEntityModule with nonce 4
executing deployment of SnapSyncModule with nonce 5
executing deployment of MapSystem with nonce 6
/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/lib/index.js:238
        var error = new Error(message);
                    ^

<ref *1> Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"cannot estimate gas; transaction may fail or may require manual gas limit","code":"UNPREDICTABLE_GAS_LIMIT","error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":51,\"error\":{\"code\":-32000,\"message\":\"gas required exceeds allowance (0)\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x59682f64\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x57fc0256434f2da202cdb77db1c6202806c0ea5f\",\"data\":\"<irrelevant_bytecode>\"}],\"id\":51,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.holesky.redstone.xyz"},"method":"estimateGas","transaction":{"from":"0x57fC0256434F2da202CdB77db1C6202806C0EA5F","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f64"},"data":"<irrelevant_bytecode>","type":2,"accessList":null}}, tx={"nonce":5,"maxPriorityFeePerGas":1500000000,"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f64"},"data":"<irrelevant_bytecode>","from":"0x57fC0256434F2da202CdB77db1C6202806C0EA5F","type":2,"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.7.0)
    at Logger.makeError (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at /Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+abstract-signer@5.7.0/node_modules/@ethersproject/abstract-signer/lib/index.js:365:47
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 6) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":51,\"error\":{\"code\":-32000,\"message\":\"gas required exceeds allowance (0)\"}}\n","error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x59682f64\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x57fc0256434f2da202cdb77db1c6202806c0ea5f\",\"data\":\"<irrelevant_bytecode>\"}],\"id\":51,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://rpc.holesky.redstone.xyz"}, method="estimateGas", transaction={"from":"0x57fC0256434F2da202CdB77db1C6202806C0EA5F","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x59682f64"},"data":"<irrelevant_bytecode>","type":2,"accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
      at Logger.makeError (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/lib/index.js:238:21)
      at Logger.throwError (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/lib/index.js:247:20)
      at checkError (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:175:16)
      at StaticJsonRpcProvider.<anonymous> (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)
      at step (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
      at Object.throw (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
      at rejected (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
    code: 'UNPREDICTABLE_GAS_LIMIT',
    error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":51,\"error\":{\"code\":-32000,\"message\":\"gas required exceeds allowance (0)\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x59682f64\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x57fc0256434f2da202cdb77db1c6202806c0ea5f\",\"data\":\"<irrelevant_bytecode>\"}],\"id\":51,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://rpc.holesky.redstone.xyz", code=SERVER_ERROR, version=web/5.7.1)
        at Logger.makeError (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+logger@5.7.0/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at /Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+web@5.7.1/node_modules/@ethersproject/web/lib/index.js:313:32
        at step (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+web@5.7.1/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+web@5.7.1/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+web@5.7.1/node_modules/@ethersproject/web/lib/index.js:5:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      reason: 'processing response error',
      code: 'SERVER_ERROR',
      body: '{"jsonrpc":"2.0","id":51,"error":{"code":-32000,"message":"gas required exceeds allowance (0)"}}\n',
      error: Error: gas required exceeds allowance (0)
          at getResult (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+providers@5.7.2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:191:21)
          at processJsonFunc (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+web@5.7.1/node_modules/@ethersproject/web/lib/index.js:356:22)
          at /Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+web@5.7.1/node_modules/@ethersproject/web/lib/index.js:288:46
          at step (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+web@5.7.1/node_modules/@ethersproject/web/lib/index.js:33:23)
          at Object.next (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+web@5.7.1/node_modules/@ethersproject/web/lib/index.js:14:53)
          at fulfilled (/Users/emersonhsieh/london-aw/emojimon/node_modules/.pnpm/@ethersproject+web@5.7.1/node_modules/@ethersproject/web/lib/index.js:5:58)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
        code: -32000,
        data: undefined
      },
      requestBody: '{"method":"eth_estimateGas","params":[{"type":"0x2","maxFeePerGas":"0x59682f64","maxPriorityFeePerGas":"0x59682f00","from":"0x57fc0256434f2da202cdb77db1c6202806c0ea5f","data":"<irrelevant_bytecode>'... 6036 more characters,
      requestMethod: 'POST',
      url: 'https://rpc.holesky.redstone.xyz'
    },
    method: 'estimateGas',
    transaction: {
      from: '0x57fC0256434F2da202CdB77db1C6202806C0EA5F',
      maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
      maxFeePerGas: BigNumber { _hex: '0x59682f64', _isBigNumber: true },
      data: '<irrelevant_bytecode>'... 5832 more characters,
      type: 2,
      accessList: null
    }
  },
  tx: {
    nonce: 5,
    maxPriorityFeePerGas: 1500000000,
    maxFeePerGas: BigNumber { _hex: '0x59682f64', _isBigNumber: true },
    data: '<irrelevant_bytecode>'... 5832 more characters,
    from: '0x57fC0256434F2da202CdB77db1C6202806C0EA5F',
    type: 2,
    gasLimit: Promise { <rejected> [Circular *1] },
    chainId: Promise { 17001 }
  }
}

Node.js v18.18.2
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by tash-2s** [comment]
The error you encountered is due to insufficient balance in your deployer account on the Redstone Holesky network. You can verify the account balance via the explorer: https://explorer.holesky.redstone.xyz.

I cloned your forked repository and successfully deployed the contracts using the same command, without making any modifications. The default account specified in the `.env` file already has some balance on the network.

Regarding the mud cli, you are using an older version. The repository has two versions of the cli. Since `/packages/contracts/package.json` specifies `"@latticexyz/cli": "2.0.0-alpha.1.177"`, this version is used for the deployment command. Additionally, a newer version of emojimon is available in the `mud-next.14` branch of the upstream repository.
