### ISSUE TITLE
MUD indexer - Issue load testing

### ISSUE THREAD

**Issue by rohanabraham** [latticexyz/mud#2313]
When we have about a million items on the records table as part of the load test and that's when we get into JSON.stringify issues, here is logs on the MUD indexer API end point.

Logs below
```
  mud:store-indexer RangeError: Invalid string length
  mud:store-indexer     at JSON.stringify (<anonymous>)
  mud:store-indexer     at <anonymous> (/home/ubuntu/tools/mud/packages/store-indexer/src/postgres/apiRoutes.ts:53:23)
  mud:store-indexer     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  mud:store-indexer     at compressMiddleware (/home/ubuntu/tools/mud/packages/store-indexer/src/koa-middleware/compress.ts:38:5)
  mud:store-indexer     at helloWorldMiddleware (/home/ubuntu/tools/mud/packages/store-indexer/src/koa-middleware/helloWorld.ts:10:5)
  mud:store-indexer     at healthcheckMiddleware (/home/ubuntu/tools/mud/packages/store-indexer/src/koa-middleware/healthcheck.ts:35:5)
  mud:store-indexer     at cors (/home/ubuntu/tools/mud/node_modules/.pnpm/@koa+cors@4.0.0/node_modules/@koa/cors/index.js:108:16) +0ms
```

<img width="996" alt="image" src="https://github.com/latticexyz/mud/assets/4366633/479379bb-e025-4cec-9248-be07b231392d">
There is an issue with this line highlighted on /packages/store-indexer/src/postgres/apiRoutes.ts

Can we do something other than stringify? Will be useful for larger projects.

**Comment by holic** [comment]
We have a revamp coming soon with streaming (#1650) and a query API (#2272)

In the meantime, you might try using table/key filters on your hydration request: https://github.com/latticexyz/mud/blob/main/packages/store-sync/src/common.ts#L75

going to close this for now as this duplicates the intent of the above two issues
