### ISSUE TITLE
Error running "forge clean"

### ISSUE THREAD

**Issue by krishaamer** [latticexyz/mud#964]
Trying to run the example project and it fails with the following errors:

```
(base) krishaamer@Kriss-MacBook-Pro-2 my-project % pnpm run dev

> mud-template-vanilla@ dev /Users/krishaamer/Desktop/current/mud/my-project
> concurrently -n contracts,client -c cyan,magenta "cd packages/contracts && pnpm run dev" "cd packages/client && pnpm run dev"

[contracts] 
[contracts] > contracts@0.0.0 dev /Users/krishaamer/Desktop/current/mud/my-project/packages/contracts
[contracts] > pnpm mud dev-contracts --tsgenOutput ../client/src/mud
[contracts] 
[client] 
[client] > client@0.0.0 dev /Users/krishaamer/Desktop/current/mud/my-project/packages/client
[client] > wait-port localhost:8545 && vite
[client] 
[client] Waiting for localhost:8545..(node:25451) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
[contracts] (Use `node --trace-warnings ...` to show where the warning was created)
[client] ....No output provided
[contracts] running "forge clean"
[contracts] null
[contracts] file:///Users/krishaamer/Desktop/current/mud/my-project/node_modules/.pnpm/@latticexyz+common@2.0.0-alpha.1.194_typescript@4.9.5_zod@3.21.4/node_modules/@latticexyz/common/dist/foundry.js:2
[contracts] Error running "${c}"`),new Error(g)}}export{F as anvil,m as cast,d as forge,n as getForgeConfig,O as getOutDirectory,w as getRpcUrl,y as getScriptDirectory,l as getSrcDirectory,x as getTestDirectory};
[contracts]                        ^
[contracts] 
[contracts] Error: dyld[25458]: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib
[contracts]   Referenced from: <28B6B4D2-A2EE-369F-A71B-D45AB2EDFA05> /Users/krishaamer/.foundry/bin/forge
[contracts]   Reason: tried: '/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/usr/local/lib/libusb-1.0.0.dylib' (no such file), '/usr/lib/libusb-1.0.0.dylib' (no such file, not in dyld cache)
[contracts] Error running "forge clean"
[contracts]     at s (file:///Users/krishaamer/Desktop/current/mud/my-project/node_modules/.pnpm/@latticexyz+common@2.0.0-alpha.1.194_typescript@4.9.5_zod@3.21.4/node_modules/@latticexyz/common/dist/foundry.js:2:24)
[contracts]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[contracts]     at async d (file:///Users/krishaamer/Desktop/current/mud/my-project/node_modules/.pnpm/@latticexyz+common@2.0.0-alpha.1.194_typescript@4.9.5_zod@3.21.4/node_modules/@latticexyz/common/dist/foundry.js:1:548)
[contracts]     at async Object.handler (file:///Users/krishaamer/Desktop/current/mud/my-project/node_modules/.pnpm/@latticexyz+cli@2.0.0-alpha.1.194_@ethersproject+bytes@5.7.0_google-protobuf@3.21.2/node_modules/@latticexyz/cli/dist/mud.js:22:2842)
[contracts] 
[contracts] Node.js v18.9.0
[contracts]  ELIFECYCLE  Command failed with exit code 1.
[contracts] cd packages/contracts && pnpm run dev exited with code 1
[client] ....................................................................

```

**Comment by krishaamer** [comment]
> Do you have foundry installed? (does it work if you run `forge --version`?) If not, you can get it from here: https://getfoundry.sh/

Thanks for the prompt reply. I did install Foundry before but it seems to miss some library...

`(base) krishaamer@Kriss-MacBook-Pro-2 my-project % forge --version
dyld[27779]: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: <28B6B4D2-A2EE-369F-A71B-D45AB2EDFA05> /Users/krishaamer/.foundry/bin/forge
  Reason: tried: '/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/usr/local/opt/libusb/lib/libusb-1.0.0.dylib' (no such file), '/usr/local/lib/libusb-1.0.0.dylib' (no such file), '/usr/lib/libusb-1.0.0.dylib' (no such file, not in dyld cache)
zsh: abort      forge --version`
